theme: jekyll-theme-slate

title: "Error Correcting Encoder-Decoder"
author: Jegors ÄŒemisovs
email: jegors.cemisovs@outlook.lv
description: >
  An implementation of the Hamming code algorithm 

# social links
twitter_username: rabestro # DO NOT include the @ character, or else the build will fail!
github_username:  rabestro # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage